[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = "^3.9"
boto3 = "^1.35.2"
psycopg2-binary = "^2.9.9"
slack-sdk = "3.27.1"

[tool.poetry.group.dev.dependencies]
pre-commit = "^3.7.0"
pytest = "^8.3.5"
moto = "^5.0.13"
pytest-cov = "^6.0.0"
